n1=int(input("enter the 1st number : "))
n2=int(input("enter the 2nd number : "))
print(f"{n1} + {n2} : {n1+n2}")
print(f"{n1} - {n2} : {n1-n2}")
print(f"{n1} * {n2} : {n1*n2}")
print(f"{n1} \ {n2} : {n1/n2}")